# Generated by Django 4.2.9 on 2024-01-27 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskResult',
        ),
    ]
