# Generated by Django 4.2.9 on 2024-01-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskResult',
        ),
    ]
